[tool.poetry]
name = "periodiq"
version = "0.9.0"
description = "Simple Scheduler for Dramatiq Task Queue"
authors = ["Ã‰tienne BERSAC"]
license = "LGPL-3.0+"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.5"
dramatiq = "^1.5"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
flake8 = "^3.7"

[tool.poetry.scripts]
periodiq = 'periodiq:entrypoint'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
